# Generated by Django 2.0.6 on 2019-05-13 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AreaCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='Monday', max_length=20)),
                ('stage', models.CharField(choices=[('ONE', 'ONE'), ('TWO', 'TWO')], default='ONE', max_length=20)),
                ('peak', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=2)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Area')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.AreaCode')),
            ],
        ),
    ]
