# Generated by Django 2.0.6 on 2019-05-13 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areacode',
            name='area',
        ),
    ]
